# Generated by Django 4.1.5 on 2023-06-28 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billingaddress",
            name="user",
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="first_name",
            field=models.CharField(
                default="Talha", max_length=150, verbose_name="First Name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="last_name",
            field=models.CharField(
                default="Malik", max_length=150, verbose_name="Last Name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="address_line_1",
            field=models.CharField(max_length=150, verbose_name="Address Line 1"),
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Address Line 1"
            ),
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="city",
            field=models.CharField(max_length=150, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="country",
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="phone_number",
            field=models.CharField(max_length=15, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="state",
            field=models.CharField(
                max_length=150, verbose_name="State/Province/Region"
            ),
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="zip_code",
            field=models.CharField(max_length=12, verbose_name="Zip Code"),
        ),
    ]
