# Generated by Django 4.1.5 on 2023-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='town_city',
            new_name='city',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(default='punjab', max_length=150),
            preserve_default=False,
        ),
    ]
