# Generated by Django 4.1.5 on 2023-06-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_town_city_billingaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='payment',
            field=models.CharField(choices=[('COD', 'Cash on Delivery')], default='COD', max_length=15),
        ),
    ]
