# Generated by Django 4.1.5 on 2023-07-08 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_newsletter"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsLetter",
        ),
    ]
