# Generated by Django 4.1.5 on 2023-06-28 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_order_billing_address"),
        ("account", "0002_remove_billingaddress_user_billingaddress_customer_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BillingAddress",
        ),
    ]
