# Generated by Django 4.1.5 on 2023-06-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_billingaddress_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name': 'Billing Address', 'verbose_name_plural': 'Billing Addresses'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='payment',
        ),
    ]
