# Generated by Django 4.1.5 on 2023-08-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimages",
            name="alt_text",
            field=models.CharField(
                default="alt text for image",
                max_length=255,
                verbose_name="Alternative text of image",
            ),
            preserve_default=False,
        ),
    ]
