# Generated by Django 4.1.5 on 2023-06-27 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="creator",
        ),
    ]
