# Generated by Django 4.1.5 on 2023-07-24 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimages",
            name="alt_text",
        ),
        migrations.RemoveField(
            model_name="productimages",
            name="is_feature",
        ),
    ]
