# Generated by Django 4.1.5 on 2023-06-28 15:06

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_remove_product_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=mptt.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="category",
                to="store.category",
            ),
        ),
    ]
