# Generated by Django 4.1.5 on 2023-08-13 14:18

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_productimages_alt_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="GridCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Category Name"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=store.models.GridCategory.user_directory_path,
                        verbose_name="Grid Category Image",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255,
                        unique=True,
                        verbose_name="Grid Category Safe URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Visibility"),
                ),
            ],
            options={
                "verbose_name": "Grid Category",
                "verbose_name_plural": "Grid Categories",
            },
        ),
    ]
