# Generated by Django 4.1.5 on 2023-08-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_gridcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="gridcategory",
            name="alt_text",
            field=models.CharField(
                default="This is an image",
                help_text="In case image is not displayed due to slow internet connection, what should be displayed instead of this image as text. Text should describe what kind of image has to be displayed",
                max_length=255,
                verbose_name="Alternative Text for Image",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productimages",
            name="alt_text",
            field=models.CharField(
                help_text="In case image is not displayed due to slow internet connection, what should be displayed instead of this image as text. Text should describe what kind of image has to be displayed. It's important for SEO.",
                max_length=255,
                verbose_name="Alternative text of image",
            ),
        ),
    ]
