# Generated by Django 4.1.5 on 2023-08-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_gridcategory_alt_text_alter_productimages_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
