# Generated by Django 4.1.5 on 2023-07-31 11:11

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.brand",
                verbose_name="Brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=mptt.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="store.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.producttype",
                verbose_name="Type of Product",
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.producttype",
                verbose_name="Type of Product",
            ),
        ),
        migrations.AlterField(
            model_name="productspecificationvalue",
            name="specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.productspecification",
            ),
        ),
    ]
