# Generated by Django 4.1.5 on 2023-08-01 08:18

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_product_brand_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=mptt.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="store.category",
            ),
        ),
    ]
