# Generated by Django 4.1.5 on 2023-08-07 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productspecificationvalue",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specification",
                to="store.product",
            ),
        ),
    ]
