# Generated by Django 4.1.5 on 2023-08-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_productspecificationvalue_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.IntegerField(default=0),
        ),
    ]
