# Generated by Django 4.1.5 on 2023-08-10 23:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_product_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_type",
        ),
    ]
