# Generated by Django 4.1.5 on 2023-08-10 23:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_remove_productspecification_product_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductType",
        ),
    ]
