# Generated by Django 4.1.5 on 2023-08-11 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_delete_producttype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productspecification",
            options={
                "verbose_name": "Product Specification",
                "verbose_name_plural": "Product Specifications",
            },
        ),
    ]
