# Generated by Django 4.1.5 on 2023-04-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_category_type_alter_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
