# Generated by Django 4.1.5 on 2023-01-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='type',
        ),
    ]
