# Generated by Django 4.1.5 on 2023-06-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaddress",
            name="default",
            field=models.BooleanField(default=False, verbose_name="Default"),
        ),
    ]
