# Generated by Django 4.1.5 on 2023-08-12 13:09

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0002_alter_billingaddress_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingaddress",
            name="country",
            field=django_countries.fields.CountryField(
                default="PK", max_length=2, verbose_name="Country"
            ),
        ),
    ]
