# Generated by Django 4.1.5 on 2023-06-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0002_billingaddress_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaddress",
            name="email",
            field=models.EmailField(
                default="talhamalik25.tm@gmail.com", max_length=254
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Address Line 2"
            ),
        ),
    ]
