# Generated by Django 4.1.5 on 2023-08-13 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_cancel_allowed",
        ),
    ]
