# Generated by Django 4.1.5 on 2023-06-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_complete',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('F', 'Fullfilled'), ('P', 'In Process')], default='P', max_length=2),
        ),
    ]
