# Generated by Django 4.1.5 on 2023-06-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_order_complete_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('D', 'Delivered'), ('P', 'In Process')], default='P', max_length=2),
        ),
    ]
