# Generated by Django 4.1.5 on 2023-08-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_remove_order_is_cancel_allowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("F", "Fullfilled"),
                    ("P", "In Process"),
                    ("C", "Is Cancelled"),
                ],
                default="P",
                max_length=2,
            ),
        ),
    ]
