# Generated by Django 4.1.5 on 2023-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_orderitemattribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                db_index=True, default="1", max_length=50, unique=True
            ),
            preserve_default=False,
        ),
    ]
