# Generated by Django 4.1.5 on 2023-08-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_order_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
