# Generated by Django 4.1.5 on 2023-06-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_billingaddress_payment'),
        ('order', '0003_remove_order_delivered_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.billingaddress'),
        ),
    ]
