# Generated by Django 4.1.5 on 2023-08-11 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_remove_order_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
