# Generated by Django 4.1.5 on 2023-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_address_line_1_order_address_line_2_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cancel_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
